name: PR open/sync

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  publish:
    name: Publish docs to AWS
    runs-on: ubuntu-22.04
    permissions:
      deployments: write
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          env: docss
      - name: update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
