name: Publish documentation for release

on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish docs to AWS
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Parse version number
        run: echo "VERSION=$(npm pkg get version | tr -d '\"')" >> "$GITHUB_ENV"
      - name: Edit Release
        uses: irongut/editrelease@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          id: ${{ github.event.release.id }}
          body: "**Documentation:** [Storybook](https://example.com/$VERSION)"
          spacing: 2
