name: Tag regex

on:
  release:
    types:
      - released
      - prereleased

jobs:
  publish:
    name: Tag regex
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Parse library version number
        run: echo "VERSION=$(npm pkg get version | tr -d '\"')" >> "$GITHUB_ENV"
      - name: Check semver
        id: check-semver
        run: |
          if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "set-as-latest=true" >> $GITHUB_OUTPUT
          fi
      - name: Is this latest
        if: steps.check-semver.outputs.set-as-latest == 'true'
        run: echo "This is latest version!"
